### ISSUE TITLE
Latest Webots release does not support --no-sandbox option anymore

### ISSUE THREAD

**Issue by astumpf** [cyberbotics/webots_ros#134]
Currently the `--no-gui` option of the webots_launcher python script is broken as it appends the apparently removed `--no-sandbox` option.

https://github.com/cyberbotics/webots_ros/blob/noetic/scripts/webots_launcher.py#L37

Is there any equivalent replacement for this option or can it just removed?

**Comment by ygoumaz** [comment]
The version of the file you are referencing ([aac8d7d](https://github.com/cyberbotics/webots_ros/commit/aac8d7d5d2bc54ceba8a88ce5fbece650885bd0c)) is very old. This option was already removed in [0866ea3](https://github.com/cyberbotics/webots_ros/pull/105/commits/0866ea314adf30df4518fddb7e7cfd7c0665cf65). The `--no-gui` option should work fine in the master branch.

**Comment by astumpf** [comment]
But the master branch seems not to be deployed under Ubuntu 20.04.

**Comment by astumpf** [comment]
Ok, then we probably need to wait until the buildfarm has run successfully. Thanks for your help!

**Comment by astumpf** [comment]
Today I got a debian package update for webots_ros. But the error remains. You can simply reproduce this issue in Ubuntu 20.04 by typing:

```
export WEBOTS_HOME=/usr/local/webots
roslaunch webots_ros webots.launch no_gui:=true
```

This still results in: `webots: invalid option: '--no-sandbox'`

Tested on multiple machines.

**Comment by ygoumaz** [comment]
The new version of the package is 2022.1.0-1. We just missed the last synchronization yesterday 15.09.2022. The package will be updated at the next sync.

Can you confirm that the version you currently tested is 5.0.1-2?

**Comment by astumpf** [comment]
> The new version of the package is 2022.1.0-1. We just missed the last synchronization yesterday 15.09.2022. The package will be updated at the next sync.
> 
> Can you confirm that the version you currently tested is 5.0.1-2?

Yes: `5.0.1-2focal.20220912.183137`

**Comment by ygoumaz** [comment]
So it is normal that you still encounter the issue. I am closing the issue. Feel free to reopen if you still encounter issues when the `2022.1.0-1` version is out.
