### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by Timple** [cyberbotics/webots_ros#17]
Would you mind releasing these packages also for the newest distribution ROS Noetic? :)

**Comment by DavidMansolino** [comment]
Yes of course, we will do so, when releasing the next version of Webots we will create a Noetic version of this package too (we have to test it first too).
But in the meantime, feel free to install it from sources: http://wiki.ros.org/webots_ros#From_Sources

**Comment by DavidMansolino** [comment]
This is now done since a few months actually https://github.com/ros/rosdistro/blob/master/noetic/distribution.yaml#L5158
