### ISSUE TITLE
Wheel velocity of differential drive robot

### ISSUE THREAD

**Issue by hcv1027** [cyberbotics/webots_ros#19]
I'm building my simulation environment by using webots to corporate with ros.
My simulated robot uses differential drive to move.
When I convert the linear & angular velocity to left/right wheel velocity, the robot's real rotation speed is not correct. Here is my code to convert linear & angular velocity to left/right wheel velocity:
```c++
void Controller::cb_cmd_vel(const geometry_msgs::Twist &msg) {
  double vel = msg.linear.x;
  double omega = msg.angular.z;
  double r_omega = (vel + omega * WHEEL_DIST / 2) / WHEEL_RADIUS;
  double l_omega = (vel - omega * WHEEL_DIST / 2) / WHEEL_RADIUS;
  ROS_INFO("cmd_vel: %f, omega: %f", vel, omega);
  ROS_INFO("r_omega: %f, l_omega: %f", r_omega, l_omega);

  webots_ros::set_float left_vel_srv;
  left_vel_srv.request.value = l_omega;
  if (left_wheel_vel_.call(left_vel_srv) &&
      left_vel_srv.response.success == 1) {
    // ROS_INFO("Left wheel velocity set to %f", l_omega);
  } else {
    ROS_ERROR("Set left wheel velocity fail");
  }

  webots_ros::set_float right_vel_srv;
  right_vel_srv.request.value = r_omega;
  if (right_wheel_vel_.call(right_vel_srv) &&
      right_vel_srv.response.success == 1) {
    // ROS_INFO("Right wheel velocity set to %f\n", r_omega);
  } else {
    ROS_ERROR("Set right wheel velocity fail");
  }
```

I set `linear velocity = 0` and `angular velocity = 0.628318` to test pure rotation, and I expect that robot should take 10 seconds to rotate a round. But it always takes about 11.6 seconds to rotate a round. Here is the [demo video link](https://youtu.be/9q-XCbtPbws). Is there anything wrong when I use the `rotation motor`?

**Comment by omichel** [comment]
I believe there is nothing wrong with your controller. Webots is a realistic simulator and because of inertia, the angular speed you are sending is a target speed, but not the effective speed of the wheel. At the beginning, the motor cannot instantly rotate at the target speed. Because of the mass of the wheel and robot, it needs some time to reach this speed. Hence the delay of 1.6 second with respect to your expectation.
