### ISSUE TITLE
webots.launch "no-gui" argument does not work

### ISSUE THREAD

**Issue by astumpf** [cyberbotics/webots_ros#30]
The no-gui argument is not forwarded by roslaunch properly due the use of a dash. Replacing "no-gui" with "no_gui" seems to solve this issue.

**Comment by omichel** [comment]
Thank you for this bug report. Could you please create a new PR here with your patch (replacement of "no-gui" with "no_gui")? We will be happy to review it and accept it.

**Comment by astumpf** [comment]
Done: https://github.com/cyberbotics/webots_ros/pull/31

:-)
