### ISSUE TITLE
Several Simulations Broken by Coordinate Change

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots_ros#37]
The switch from NUE to ENU was done only at the world level #36, but the controllers were not updated, this, unfortunately, broke several simulations:

### pioneer3at

The laser scan orientation is now wrongly oriented, generating a completely random map:
![Capture du 2020-10-28 08-14-09](https://user-images.githubusercontent.com/2461619/97404399-54e13980-18f6-11eb-8fa7-3d4d827eea65.png)

### panoramic_view_recorder

The controller is rotating the viewpoint aroud the vertical axis of the robot, but since the vertical axis is not the same anymore, the viewpoint is not looking at the robot anymore while rotating:
![Capture du 2020-10-28 08-14-43](https://user-images.githubusercontent.com/2461619/97404514-878b3200-18f6-11eb-8ccf-1df8a48afeef.png)

### complete_test

This simulation is supposed (among other) to show how to communicate with the robot window from a ros controller, but the robot-window was closed in the world project file: https://github.com/cyberbotics/webots_ros/pull/36/files#diff-11ad9c9c91148e9eba152d3450d94d224348d22115d4dd0eb3870ec050ce9d6dL9

### all

The coordinates axes optional rendering was enabled in the world project files (https://github.com/cyberbotics/webots_ros/pull/36/files#diff-9c8028e5e83f34ceb703bc77b8dc4fcce19a33661046fe89a132508f9b41adecR9), this doesn't break anything, but I am wondering if this was made on purpose or if this is just an artefact of checking the axes?

### other

After such a PR it is good to make a dual PR on the https://github.com/cyberbotics/webots repository to synchronize it with this repo.

**Comment by lukicdarkoo** [comment]
This is solved in:
- https://github.com/cyberbotics/webots/pull/2424
- https://github.com/cyberbotics/webots_ros/pull/38
- https://github.com/cyberbotics/webots_ros/pull/39
