### ISSUE TITLE
Release of packages for Webots R2021a

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots_ros#49]
The develop branch was correctly merged in the master branch of this repository after releasing Webots R2021a, but it seems the packages were never actually released.

It is quite important to release the packages soon after releasing a major version of Webots so that the packages stay synchronized with the latest version of Webots (particularly for ROS1 as Webots is not bounded with the packages).

**Comment by lukicdarkoo** [comment]
Thank you @DavidMansolino! I guess we should publish it for Melodic and Noetic only?

**Comment by DavidMansolino** [comment]
You're welcome.
Maybe a last release for kinetic too (as it is still maintained for a few months and used but quickly decreasing: https://metrics.ros.org/rosdistro_rosdistro.html ) doesn't cost much.

**Comment by lukicdarkoo** [comment]
Published, waiting for sync.

P.S. I jumped one major number ahead, the bloom release was failing with 3.0.0 for some reason.

**Comment by lukicdarkoo** [comment]
The PRs on `rosdistro` are merged, I will close the issue
