### ISSUE TITLE
Unable to launch the files

### ISSUE THREAD

**Issue by SunnyKatyara** [cyberbotics/webots_ros#7]
Hello, i have cloned this repo into my catkin/src workspace and when i launch any of the files, its showing nothing, although webots is starting, as shown in Fig.

![Screenshot from 2019-09-23 17-14-24](https://user-images.githubusercontent.com/52322093/65438362-a7177780-de25-11e9-99af-a3c4d608e1a9.png)

What can be the issue...I have sourced all the files but still this issue.

Thank You

**Comment by DavidMansolino** [comment]
I assume you found the reason of the problem?

**Comment by SunnyKatyara** [comment]
yes i found the reason. It was my path issue. solved it. But now facing issue with the robot falling down when i start the simulation.
