### ISSUE TITLE
Warnings in complete_test

### ISSUE THREAD

**Issue by BenjaminHug8** [cyberbotics/webots_ros#87]
Several warnings come in the Webots console when launching the `complete_test`.
Most probably the commands sent with ROS have values out of bounds for the motors.

**Comment by lukicdarkoo** [comment]
I only saw the accelerometer warnings. Let me know if there is any other.

**Comment by BenjaminHug8** [comment]
In the console of Webots I got the following:
![Screenshot from 2021-11-17 08-32-18](https://user-images.githubusercontent.com/61198898/142155793-842dc0cc-6c55-4d1b-9986-0e620d813ce2.png)

**Comment by lukicdarkoo** [comment]
No warnings with Webots R2021b-rev1. Which version do you use?

**Comment by BenjaminHug8** [comment]
I am using the `master` branch.

**Comment by lukicdarkoo** [comment]
I see it now, I am getting it the same errors as well, this code block was pausing the simulation (I will check it as well):
```bash
    sub_GPS_speed = n.subscribe(model_name + "/gps/speed", 1, GPSSpeedCallback);
    callbackCalled = false;
    while (sub_GPS_speed.getNumPublishers() == 0 || !callbackCalled) {
      ros::spinOnce();
      time_step_client.call(time_step_srv);
    }
```
