### ISSUE TITLE
Subscriber for Devices

### ISSUE THREAD

**Issue by machinekoder** [cyberbotics/webots_ros#9]
This issue is a suggestion rather than a bug.

Currently, devices, such for example a motor, can only be set using a ROS service call. However, in some cases, it might be more useful to have an ROS Subscriber interface to update the simulation value.

For example, in my recent simulation, I simulate a 6-DOF robot manipulator. For this purpose, I convert the `/joint_states` message to the corresponding ROS service calls to update the motor. Since service calls are synchronous in roscpp, I had to use an AsyncSpinner to make things work smoothly.

However, would there be a Subscriber interface for updating the motor position, the whole task would have been a lot simpler.

**Comment by DavidMansolino** [comment]
@machinekoder thank you for this pertinent suggestion, it does indeed perfectly make sense, we are currently creating an interface with ROS2 for Webots: https://github.com/cyberbotics/webots_ros2
We will for sure keep your suggestion in mind while creating this interface!
